title: "touyama"
description: "\u30B2\u30FC\u30E0\u30D7\u30ED\u30B0\u30E9\u30DE\u30FC"
lang: ja
timezone: Asia/Tokyo
url: "https://touyamakou.github.io"
baseurl: ""
permalink: /posts/:title/

brand:
  title: "Draft"
  icon_text: "T"
  icon_image: "/assets/images/logo.png"
  url: "/"

profile:
  name: "touyama"
  bio: "\u30B2\u30FC\u30E0\u30D7\u30ED\u30B0\u30E9\u30DE\u30FC"
  avatar: "https://static.zenn.studio/user-upload/avatar/2e5899f7fb.jpeg"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "touyama"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
