title: "touyama"
description: "ゲームプログラマー"
lang: ja
timezone: Asia/Tokyo
url: "https://touyamakou.github.io"
baseurl: ""
permalink: /posts/:title/

profile:
  name: "touyama"
  handle: "@touyama"
  bio: "ゲームプログラマー"
  avatar: "https://static.zenn.studio/user-upload/avatar/2e5899f7fb.jpeg"
  location: ""
  links:
    rss: "/feed.xml"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "touyama"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock